# Generated by Django 2.2.5 on 2019-12-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.FloatField()),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=64)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Graph')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
