version: '3.7'
name: GraphTemplateSite-dev

services:
    web:
        build:
            context: .
            dockerfile: docker/dev/web.dockerfile
        command: gunicorn --bind 0.0.0.0:8000 --chdir server entrypoint.wsgi:application
        ports:
            - 8000:8000
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: docker/dev/pg.dockerfile
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - PGUSER=${SQL_USER}
            - PGPASSWORD=${SQL_PASSWORD}
            - PGDATABASE=${SQL_DATABASE}
            - POSTGRES_USER=${SQL_USER}
            - POSTGRES_PASSWORD=${SQL_PASSWORD}
            - POSTGRES_DB=${SQL_DATABASE}
volumes:
    postgres_data:
