version: '3.7'
name: GraphTemplateSite-prd

services:
    web:
        build:
            context: .
            dockerfile: docker/prd/web.dockerfile
        command: gunicorn --bind 0.0.0.0:8000 --chdir server entrypoint.wsgi:application
        ports:
            - 8000:8000
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: docker/prd/pg.dockerfile
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
    nginx:
        build:
            context: .
            dockerfile: docker/prd/nginx.dockerfile
        ports:
            - 80:80
        expose:
            - 80
        depends_on:
            - web
volumes:
    postgres_data:
