version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/${DOCKER_FILE}
    command: gunicorn --bind 0.0.0.0:8000 --chdir ./server entrypoint.wsgi:application
#    volumes:
#      - ../server:/app/server
#      - ../client:/app/client
    ports:
      - 8000:8000
    environment:
      - SQL_USER=${DB_USER}
      - SQL_PASSWORD=${DB_PASSWORD}
      - SQL_DATABASE=${DB_NAME}
    env_file:
      - ./dev/web.dev.env
    depends_on:
      - db
  db:
    build:
      context: ..
      dockerfile: ./docker/${DOCKER_FILE_PG}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGDATABASE=${DB_NAME}
volumes:
  postgres_data:
