# Generated by Django 3.0.2 on 2020-01-17 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20200116_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='sub_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
