# Generated by Django 3.0.2 on 2020-01-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200117_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='description',
        ),
        migrations.AddField(
            model_name='graph',
            name='description',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='x_label',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='y_label',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
